"""MK1 reframing helpers for platform_safe_format_v1.

Face-track crop rendering will be added in later prompts. Today this package
owns shared reframe constants, strategy planning, the blurred-background
fallback FFmpeg command builder, and optional face-detection helpers.
"""

from reframing.config import (
    DEFAULT_FACE_TRACK_TEST_ENABLED,
    DEFAULT_REFRAME_MODE,
    FACE_TRACK_SKIP_REASON_TEST_DISABLED,
    FORMAT_STRATEGY_BLURRED_BACKGROUND,
    FORMAT_STRATEGY_FACE_TRACK_CROP,
    REFRAME_MODE_AUTO,
    REFRAME_MODE_BLUR_BACKGROUND,
    REFRAME_MODE_FACE_TRACK,
    REFRAME_MODES,
    resolve_face_track_test_enabled,
    resolve_reframe_plan,
    validate_reframe_mode,
)
from reframing.detector import (
    DEFAULT_DETECTION_FPS,
    DEFAULT_DETECTOR_BACKEND,
    DEFAULT_MIN_FACE_CONFIDENCE,
    build_sample_frames_command,
    detect_faces,
    detect_faces_for_clip,
    detector_backend_available,
    mediapipe_import_status,
    merge_detector_config,
    sample_frames,
    write_detection_report,
)
from reframing.crop_path_planner import (
    build_crop_path_from_track,
    build_face_crop_path_for_clip,
    compute_max_crop_dimensions,
    crop_path_metadata,
    merge_crop_planner_config,
    position_crop_for_face,
    write_crop_path_report,
)
from reframing.fallback import build_blur_background_command
from reframing.eligibility import (
    evaluate_face_track_eligibility,
    face_track_eligibility_metadata,
    merge_eligibility_config,
    write_eligibility_report,
)
from reframing.renderer import (
    build_concat_command,
    build_face_track_render_plan,
    build_segment_command,
    build_segment_intervals,
    face_track_render_metadata,
    merge_renderer_config,
    plan_render_segments_from_crop_path,
    render_face_track_crop,
    validate_smoothed_crop_for_render,
    write_concat_list,
)
from reframing.smoother import (
    build_smoothed_face_crop_path_for_clip,
    merge_smoother_config,
    smooth_crop_path,
    smoothed_crop_path_metadata,
    write_smoothed_crop_path_report,
)
from reframing.tracker import (
    build_face_track_for_clip,
    build_primary_face_track,
    face_pipeline_metadata,
    merge_tracker_config,
    write_track_report,
)
from reframing.types import (
    BoundingBox,
    CropPathReport,
    CropPathSample,
    CropRect,
    DetectionReport,
    FaceDetection,
    FaceTrackEligibilityReport,
    FaceTrackRenderResult,
    FrameSample,
    RenderSegment,
    RenderSegmentPlanStats,
    TrackReport,
    TrackedFaceSample,
)

__all__ = [
    "DEFAULT_DETECTION_FPS",
    "DEFAULT_DETECTOR_BACKEND",
    "DEFAULT_MIN_FACE_CONFIDENCE",
    "DEFAULT_REFRAME_MODE",
    "BoundingBox",
    "CropPathReport",
    "CropPathSample",
    "CropRect",
    "DetectionReport",
    "FaceDetection",
    "FaceTrackEligibilityReport",
    "FaceTrackRenderResult",
    "FORMAT_STRATEGY_BLURRED_BACKGROUND",
    "FORMAT_STRATEGY_FACE_TRACK_CROP",
    "FrameSample",
    "RenderSegment",
    "RenderSegmentPlanStats",
    "REFRAME_MODE_AUTO",
    "REFRAME_MODE_BLUR_BACKGROUND",
    "REFRAME_MODE_FACE_TRACK",
    "REFRAME_MODES",
    "TrackReport",
    "TrackedFaceSample",
    "build_blur_background_command",
    "build_concat_command",
    "build_crop_path_from_track",
    "build_face_crop_path_for_clip",
    "build_face_track_for_clip",
    "build_face_track_render_plan",
    "build_primary_face_track",
    "build_sample_frames_command",
    "build_segment_command",
    "build_segment_intervals",
    "build_smoothed_face_crop_path_for_clip",
    "compute_max_crop_dimensions",
    "detect_faces",
    "detect_faces_for_clip",
    "detector_backend_available",
    "crop_path_metadata",
    "face_pipeline_metadata",
    "evaluate_face_track_eligibility",
    "face_track_eligibility_metadata",
    "face_track_render_metadata",
    "mediapipe_import_status",
    "merge_crop_planner_config",
    "merge_detector_config",
    "merge_eligibility_config",
    "merge_renderer_config",
    "merge_smoother_config",
    "merge_tracker_config",
    "position_crop_for_face",
    "plan_render_segments_from_crop_path",
    "render_face_track_crop",
    "resolve_reframe_plan",
    "sample_frames",
    "smooth_crop_path",
    "smoothed_crop_path_metadata",
    "validate_reframe_mode",
    "validate_smoothed_crop_for_render",
    "write_concat_list",
    "write_crop_path_report",
    "write_detection_report",
    "write_eligibility_report",
    "write_smoothed_crop_path_report",
    "write_track_report",
]
