"""Baseline defaults for simplified funnel creation (Funnel Management MK1)."""

from __future__ import annotations

from .schema import (
    DEFAULT_CONFIG_MANAGER_PRESET,
    DEFAULT_MAX_VIDEOS_PER_SOURCE,
)

BASELINE_TEMPLATE_ID = "baseline_stream_clips"
BASELINE_AI_RULE_PROFILE = "business"
BASELINE_CREATE_STATUS = "testing"
BASELINE_CREATE_ENABLED = True
BASELINE_ENVIRONMENT = "dev"
BASELINE_MAX_CLIPS = 2
BASELINE_MIN_CLIP_SEC = 10
BASELINE_MAX_CLIP_SEC = 90

DEFAULT_CREATE_CONFIG_MANAGER_PRESET = DEFAULT_CONFIG_MANAGER_PRESET
DEFAULT_CREATE_MAX_VIDEOS_PER_SOURCE = DEFAULT_MAX_VIDEOS_PER_SOURCE
